# Generated by Django 3.2.8 on 2022-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_tg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='surname')),
                ('about', models.TextField(null=True, verbose_name='description')),
                ('photo', models.TextField(null=True, verbose_name='photo_id')),
            ],
            options={
                'verbose_name': 'Пользователь тг',
                'verbose_name_plural': 'Пользователи тг',
            },
        ),
    ]
