# Generated by Django 3.2.8 on 2022-05-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_user_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название чата')),
            ],
            options={
                'verbose_name': 'Гильдия',
                'verbose_name_plural': 'Гильдии',
            },
        ),
        migrations.AddField(
            model_name='user_tg',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='username'),
        ),
    ]
