# Generated by Django 3.2.8 on 2022-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20220514_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tg',
            name='tg_id',
            field=models.TextField(default=0, verbose_name='tg_id'),
            preserve_default=False,
        ),
    ]
